CREATE USER 'bamboouser'@'192.168.1.21' IDENTIFIED BY 'St4rbuck';
CREATE DATABASE bamboo CHARACTER SET utf8 COLLATE utf8_bin;
GRANT ALL PRIVILEGES ON bamboo.* TO 'bamboouser'@'192.168.1.21' IDENTIFIED BY 'St4rbuck';
FLUSH PRIVILEGES;
